DROP TYPE Pain_t FORCE;
DROP TYPE Pain_Special_t FORCE;
DROP TYPE List_of_fromages_t FORCE;
DROP TYPE Fromage_t FORCE;
DROP TYPE Adresse_t FORCE;
DROP TYPE Client_t FORCE;
DROP TYPE Vin_t FORCE;
DROP TYPE Charcuterie_t FORCE;
DROP TYPE Jambon_t FORCE;
DROP TYPE Pate_t FORCE;
DROP TYPE Saucisse_t FORCE;

DROP TABLE Client;
DROP TABLE Repas;
